baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Homepage"
[taxonomies]
  category = 'categories'
  tag = 'tags'
  news = 'news'
  event = 'events'
  completedEvent = 'completedEvents'
