backend:
  name: git-gateway

media_folder: "site/static/img"
public_folder: "img"

taxonomies:
  category: categories
  tag: tags
  event: events
  completedEvent: completedEvents

collections:
  - name: "news-updates"
    label: "News Updates"
    folder: "site/content/news/news-updates"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Article Link", name: "text", widget: "text"}
      - {label: "Kind of event", name: "tags", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}


  - name: "news-technicals"
    label: "News Technicals"
    folder: "site/content/news/news-technicals"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Article Link", name: "text", widget: "text"}
      - {label: "Kind of event", name: "tags", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}


  - name: "events-workshop"
    label: "Events Workshop"
    folder: "site/content/events/events-workshop"
    create: true
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Workshop Link", name: "text", widget: "text"}
      - {label: "Kind of event", name: "events", widget: "string"}
      - {label: "Location", name: "location", widget: "text", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}


  - name: "events-meetups"
    label: "Events Meetups"
    folder: "site/content/events/events-meetups"
    create: true
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Meetup Link", name: "text", widget: "text"}
      - {label: "Kind of event", name: "events", widget: "string"}
      - {label: "Location", name: "location", widget: "text", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}


  - name: "events-amas"
    label: "Events AMAs"
    folder: "site/content/events/events-amas"
    create: true
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "AMA Link", name: "text", widget: "text"}
      - {label: "Kind of event", name: "events", widget: "string"}
      - {label: "Location", name: "location", widget: "text", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}


  - name: "events-workshop-completed"
    label: "Completed Events Workshop"
    folder: "site/content/events-completed/events-workshop"
    create: true
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Workshop link text", name: "linkText", widget: "text", required: false}
      - {label: "Workshop link", name: "link", widget: "text", required: false}
      - {label: "Event tag (completed + event name)", name: "completedEvents", widget: "string"}
      - {label: "Kind of event", name: "description", widget: "string"}
      - {label: "Location", name: "location", widget: "text", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Event video", name: eventVideo, widget: list, fields: [
          {label: "Event video image", name: "videoImage", widget: "image"},
          {label: "Event video link", name: "videoLink", widget: "text"}]}
      - {label: "Event photo", name: eventImage, widget: list, fields: [
          {label: "Event image", name: "image", widget: "image"}]}


  - name: "events-meetups-completed"
    label: "Completed Events Meetups"
    folder: "site/content/events-completed/events-meetups"
    create: true
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Meetup link text", name: "linkText", widget: "text", required: false}
      - {label: "Meetup link", name: "link", widget: "text", required: false}
      - {label: "Event tag (completed + event name)", name: "completedEvents", widget: "string"}
      - {label: "Kind of event", name: "description", widget: "string"}
      - {label: "Location", name: "location", widget: "text", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Event video", name: eventVideo, widget: list, fields: [
          {label: "Event video image", name: "videoImage", widget: "image"},
          {label: "Event video link", name: "videoLink", widget: "text"}]}
      - {label: "Event photo", name: eventImage, widget: list, fields: [
          {label: "Event image", name: "image", widget: "image"}]}


  - name: "events-amas-completed"
    label: "Completed Events AMAs"
    folder: "site/content/events-completed/events-amas"
    create: true
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "AMA link text", name: "linkText", widget: "text", required: false}
      - {label: "AMA link", name: "link", widget: "text", required: false}
      - {label: "Event tag (completed + event name)", name: "completedEvents", widget: "string"}
      - {label: "Kind of event", name: "description", widget: "string"}
      - {label: "Location", name: "location", widget: "text", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Event video", name: eventVideo, widget: list, fields: [
          {label: "Event video image", name: "videoImage", widget: "image"},
          {label: "Event video link", name: "videoLink", widget: "text"}]}
      - {label: "Event photo", name: eventImage, widget: list, fields: [
          {label: "Event image", name: "image", widget: "image"}]}


  - name: "pages"
    label: "Pages"
    editor:
      preview: true
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Top banner", name: banner, widget: object, fields: [
              {label: "Title", name: "title", widget: string},
              {label: "Subtitle", name: "subtitle", widget: "text"}]}
          - {label: "About", name: about, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Easy to develop", name: develop, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "markdown"}]}
          - {label: "Products", name: products, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Easy to scale", name: scale, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "markdown"}]}
          - {label: "Use cases", name: cases, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "markdown"}]}
          - {label: "Community", name: community, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "markdown"}]}